Tab component
navikt/crm-nks-base pull request #1473
Opened 2023-11-03 10:31 UTC by mamikals

2023-11-06 10:15 UTC, saramoh2309 approved these changes

2023-11-09 10:16 UTC, EirikFladby requested changes
Very nice 😄 

Noen ting jeg la merke til:
1. Utbetaling har ikke "Siste måned" auto selected
2. Bør ha feedback (loading indikator) når man trykker Refresh på henvendelser
3. Kolonne-bredde resettes når man sorterer på henvendelser
4. Kan ikke sortere på NAV Enhet og Navn?
5. Dato vises nå som "18.Sep.2022" istedenfor "18.9.2022". Personlig syns jeg siste er enklest å lese for å få oversikt fort, vet ikke om du har snakket med Sara So om dette?
6. Bør øke antall henvendelser som vises i første omgang, nå vises 10, men her vises kun 3 av gangen
7. Blå logo for "Åpen" er mindre og større mellomrom mellom "Åpen". Ikke noe big deal tho.
8. Hvorfor er prioritet "HOY" og ikke "HØY"? Ikke noe i din PR, men la merke til det.


Er nok bare 1, 2, 5 og 6 som MÅ ses på før release though.

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +            return;
Kan vi heller ha en else evt. else-if her? 😃

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +    }
Kan vi slå sammen disse med koden i connectedCallback maybe? Slippe å gjøre same if/else 3 ganger. Kan jo gjøre alt dette i én metode som kjører i connected og sette variabler utifra det elns. Disse trenger jo strengt tatt ikke å være getters da objectApiName vil være statisk per record page?

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +            console.log('error: ');
Fjern. Erstatt linje 82 med console.error hvis det trengs å logge error

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +            console.log('error: ');
Fjern. Erstatt linje 82 med console.error hvis det trengs å logge error

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +            console.log('error:');
Fjern. Erstatt linje 82 med console.error hvis det trengs å logge error

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +        return this.actorId != null;
Skader ikke å bruke !== 😄

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +        return this.movedCountry != null;
Skader ikke å bruke !== 😄

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +    }
Fjern

2023-11-09 10:16 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +        console.log('Bink');
Fjern 🤣

2023-11-09 10:17 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +    // TODO: Use labels for english/norwegian
Fjern TODO

2023-11-09 10:57 UTC, mamikals commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +            return;
Sure, det blir jo basically det samme 😄

2023-11-09 12:39 UTC, EirikFladby commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +            return;
Gir bare mer mening i hodet mitt, også om man skulle utvidet etter hvert og legge til flere cases

2023-11-09 13:09 UTC, mamikals commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +        return this.movedCountry != null;
Jo faktisk så gjør det det i dette tilfelle, en != mot null sjekker også etter tilfeller av undefined, mens !== sjekker bare mot null

2023-11-09 13:09 UTC, mamikals commented on force-app/main/default/lwc/nksPersonTab/nksPersonTab.js
> +        return this.actorId != null;
Jo faktisk så gjør det det i dette tilfelle, en != mot null sjekker også etter tilfeller av undefined, mens !== sjekker bare mot null

2025-06-13 12:36 UTC, closed without merging