Nks 1730
navikt/crm-nks-base pull request #1557
Opened 2024-03-21 22:10 UTC by saramoh2309

2024-04-08 06:06 UTC, mamikals requested changes
Hva er poenget med å legge til alt dette for livechattranscript? Skal vi flytte det eller?

2024-04-08 06:06 UTC, mamikals commented on force-app/main/default/classes/NKS_FamilyViewController.cls
> +        }
Her burde det være en null check så vi får en exception

2024-04-08 06:06 UTC, mamikals commented on force-app/nksAddresses/classes/NKS_AddressController.cls
> +            .Account.CRM_Person__c;
Her og

2024-04-19 09:48 UTC, saramoh2309 commented
> Hva er poenget med å legge til alt dette for livechattranscript? Skal vi flytte det eller?

Det er for å kunne vise bostedadresse og familie-komponentene i chat (under detaljer fanen), det er ikke behov for flytting nei

2024-04-30 11:40 UTC, closed without merging