homepagelistrefactor
navikt/crm-nks-base pull request #1588
Opened 2024-06-21 12:02 UTC by EirikFladby

2024-06-24 05:24 UTC, mamikals requested changes

2024-06-24 05:24 UTC, mamikals commented on force-app/nksHomePage/lwc/nksHomePageList/nksHomePageList.js
> +        }, rand);
Koffer e detta en timeout?

2024-06-24 05:24 UTC, mamikals commented on force-app/nksHomePage/lwc/nksHomePageList/nksHomePageList.js
> +                this.setupEmpSubscription();
E det noe grunn til å vente med å subscribe til etter vi har henta dataen? Og denna kommer vel te å gå i en insane loop, fordi hver nytt emp call kommer til å kjøre subscribe igjen. Det må legges inn en sjekk her på om vi e subscribed, enten her eller i metoden.

2024-06-28 13:00 UTC, EirikFladby commented
@saramoh2309 Muligens noe du kan teste mens du jobber med hjemskjermen ila. sommern? 😄

2024-08-07 10:27 UTC, saramoh2309 commented
> @saramoh2309 Muligens noe du kan teste mens du jobber med hjemskjermen ila. sommern? 😄
Så ikke dette før i dag. Skal teste litt jeg også :)

2024-08-07 11:45 UTC, saramoh2309 commented on force-app/nksHomePage/lwc/nksHomePageList/nksHomePageList.js
> +        return this.objectName === 'NKS_Announcement__c' && this.filter && this.filter.includes('News');
Her this.filter kan gjerne fjernes (man får varsel fra sonarLint): 
`        return this.objectName === 'NKS_Announcement__c' && this.filter?.includes('News');
`

2024-08-07 11:47 UTC, saramoh2309 commented on force-app/nksHomePage/lwc/nksHomePageList/nksHomePageList.js
> +        return (this.objectName === 'LiveChatTranscript' || this.isSTO) ? this.records.length - 1 : 0;
Her parenteser kan gjerne fjernes

2024-08-07 11:48 UTC, saramoh2309 commented on force-app/nksHomePage/lwc/nksHomePageList/nksHomePageList.js
> +            sortedList.sort((a, b) => (b.pin === a.pin ? 0 : b.pin ? 1 : -1));
Denne linjen bør gjerne omskrives til (man får varsel fra sonarLint): 
`sortedList.sort((a, b) => {
                if (b.pin === a.pin) {
                    return 0;
                }
                return b.pin ? 1 : -1;
            });`

2024-08-07 12:49 UTC, saramoh2309 approved these changes
Testet i sit; endringer ser bra ut :)

2024-08-09 11:03 UTC, merged