Changing button to create Nav task if no access to person
navikt/crm-nks-base pull request #1599
Opened 2024-07-08 11:38 UTC by vegarduri

2024-07-08 12:05 UTC, mamikals requested changes
Ser veldig bra ut, men kan ryddes litt opp i antall mtp. recordId

2024-07-08 12:05 UTC, mamikals commented on force-app/main/default/lwc/nksConversationNoteDetails/nksConversationNoteDetails.js
> +import { LightningElement, api, wire, track } from 'lwc';
Track brukes ikke

2024-07-08 12:05 UTC, mamikals commented on force-app/main/default/lwc/nksConversationNoteDetails/nksConversationNoteDetails.js
> +    }
Denne er vel ikke nødvendig? Den henter jo bare ut id fra recorden vi er på, som vil være det samme som recordId

2024-07-08 12:05 UTC, mamikals commented on force-app/main/default/lwc/nksConversationNoteDetails/nksConversationNoteDetails.js
> +    }
Dette kan være en wire metode i stedet for, der relationshipField er hardkodet til 'Account.CRM_Person__c'

2024-07-08 13:40 UTC, saramoh2309 commented on force-app/main/default/lwc/nksConversationNoteDetails/nksConversationNoteDetails.js
> +    }
Kan denne funksjonen flyttes til nksButtonContainerUtils for å unngå gjentakelse av funksjonen i forskjellige komponenter/repoer? Vi kan rename funksjonen til for eks. nksComponentUtils og importere resolve funksjonen i de forskjellige komponentene :)

2024-07-09 11:19 UTC, mamikals approved these changes

2024-07-09 11:52 UTC, merged